
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ruby_capstone_demo_development

test:
  <<: *default
  database: ruby_capstone_demo_test

production:
